// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TMS.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TMS.Infrastructure.Data.TMSDbContext))]
    [Migration("20260515170500_AddRowVersionToRequestApprovals")]
    partial class AddRowVersionToRequestApprovals
    {
    }
}
